language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm ci
` 
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"  

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend femilawal/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push femilawal/udagram-frontend